apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dp78k18xa-python 
  janus-idp.io/tekton: dp78k18xa-python
  backstage.io/kubernetes-id: dp78k18xa-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dp78k18xa-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml