apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dp78k18xa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dp78k18xa-python 
  name: dp78k18xa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dp78k18xa-python 
